[versions]
alchemist = "33.1.0"
kotlin = "1.9.23"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-maps = { module = "it.unibo.alchemist:alchemist-maps", version.ref = "alchemist" }
alchemist-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist" }

[bundles]
alchemist = [ "alchemist", "alchemist-scafi", "alchemist-maps" ]

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.4" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.61.0" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.5.8" }
taskTree = { id = "com.dorongold.task-tree", version = "3.0.0" }
